# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: 預編譯

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 設定 Swift 版本
      uses: swift-actions/setup-swift@v1.19.0
      with:
        swift-version: 5.7
    
    - name: 建構
      run: swift build -c release --arch arm64 --arch x86_64
      
    - name: 檢查工作資料夾
      run: ls -al
      
    - name: 檢查檔產生位置
      run: cd .build/apple/Products/Release; ls -al; cd ../../../../..; ls -al
  
    - name: 確認目前位置
      run: pwd

    - name: 使用搬移腳本
      run: ./Tool/setup_formater.sh
      
    - name: 檢查結果
      run: ls -al Per-Build; cat Per-Build/formater.artifactbundle/info.json; ls Per-Build/formater.artifactbundle/formater-0.50.3-macos/bin/
