# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test01

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1
    - name: Get swift version
      run: swift --version # Swift 5.7
    
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -c DEBUG
